In [14]:
# Импорт библиотек 
import numpy as np

from openneuron.units import Neuron
from openneuron.layers import Layer
from openneuron.models import NeuralNetwork
from openneuron.optimizers import SGD, Adam
from openneuron.functions import *
from openneuron.activations import *
from openneuron.utils import *

In [15]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=4, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

nn = NeuralNetwork([
    Layer([
        Neuron(weights=[-1.01, 0.05], bias=-0.09),
        Neuron(weights=[0.02, -2.06], bias=0.10),
    ], activation=swish),
    Layer([
        Neuron(weights=[-3.03, 0.07], bias=-0.11),
        Neuron(weights=[0.04, -4.08], bias=0.12),
    ], activation=softmax)
], inputs_dim=inputs_dim, loss='categorical_crossentropy', optimizer=None)

nn.fit(X_train, y_train, learning_rate=0.75, epochs=10)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{predictions}')

network_summary(nn)

Training started with Overall Loss 0.7642
Epoch 1/10, Loss: 1.3110, Validation Loss: 0.6908
Epoch 2/10, Loss: 0.8865, Validation Loss: 0.5879
Epoch 3/10, Loss: 0.7894, Validation Loss: 0.4420
Epoch 4/10, Loss: 0.6001, Validation Loss: 0.3819
Epoch 5/10, Loss: 0.5104, Validation Loss: 0.3369
Epoch 6/10, Loss: 0.4238, Validation Loss: 0.3202
Epoch 7/10, Loss: 0.4066, Validation Loss: 0.2920
Epoch 8/10, Loss: 0.3563, Validation Loss: 0.2613
Epoch 9/10, Loss: 0.3271, Validation Loss: 0.2510
Epoch 10/10, Loss: 0.3233, Validation Loss: 0.2360
Training completed with Overall Loss 0.2360
Predictions:
[[0.089  0.911 ]
 [0.5498 0.4502]
 [0.9979 0.0021]
 [0.2216 0.7784]]
Network type: "Classification", layers: 2, neurons: 4, optimizer: None, epochs: 10, batch size: 1, loss function: "Categorical Crossentropy"
Layer 1, neurons: 2, activation: swish
Neuron 1, inputs: [1 1], weights: [-1.5301 -1.7342], bias: 0.3249, z: -2.9393, activation: swish, a: -0.1477
Neuron 2, inputs: [1 1], weights: [ 2.4807

In [16]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(4, activation=swish),
    Layer(2, activation=softmax)
], inputs_dim=inputs_dim, loss='categorical_crossentropy', optimizer=Adam())

nn.fit(X_train, y_train, learning_rate=1, epochs=10, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{predictions}')

network_summary(nn)

Training started with Overall Loss 0.7128
Epoch 1/10, Loss: 1.1185, Validation Loss: 0.7689
Epoch 2/10, Loss: 0.7775, Validation Loss: 0.7300
Epoch 3/10, Loss: 0.7303, Validation Loss: 0.7067
Epoch 4/10, Loss: 0.7130, Validation Loss: 0.6951
Epoch 5/10, Loss: 0.7074, Validation Loss: 0.6934
Epoch 6/10, Loss: 0.7077, Validation Loss: 0.6952
Epoch 7/10, Loss: 0.7103, Validation Loss: 0.6947
Epoch 8/10, Loss: 0.7130, Validation Loss: 0.6927
Epoch 9/10, Loss: 0.7171, Validation Loss: 0.6909
Epoch 10/10, Loss: 0.7203, Validation Loss: 0.6900
Training completed with Overall Loss 0.6900
Predictions:
[[0.52 0.48]
 [0.49 0.51]
 [0.5  0.5 ]
 [0.47 0.53]]
Network type: "Classification", layers: 2, neurons: 6, optimizer: "Adam", epochs: 10, batch size: 1, loss function: "Categorical Crossentropy"
Layer 1, neurons: 4, activation: swish
Neuron 1, inputs: [1 1], weights: [0.   0.05], bias: -0.0486, z: 0.0043, activation: swish, a: 0.0022
Neuron 2, inputs: [1 1], weights: [-0.12 -0.11], bias: 0.0965, 

In [54]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(2, activation=swish),
    Layer(1, activation=sigmoid)
], inputs_dim=inputs_dim, loss='mse', optimizer=Adam())

nn.fit(X_train, y_train, learning_rate=1, epochs=20, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{np.round(predictions)}')

network_summary(nn)

Training started with Overall Loss 0.2635
Epoch 1/20, Loss: 0.3172, Validation Loss: 0.2498
Epoch 3/20, Loss: 0.2556, Validation Loss: 0.2501
Epoch 5/20, Loss: 0.2540, Validation Loss: 0.2499
Epoch 7/20, Loss: 0.2544, Validation Loss: 0.2498
Epoch 9/20, Loss: 0.2547, Validation Loss: 0.2492
Epoch 11/20, Loss: 0.2538, Validation Loss: 0.2459
Epoch 13/20, Loss: 0.2397, Validation Loss: 0.2162
Epoch 15/20, Loss: 0.1668, Validation Loss: 0.1441
Epoch 17/20, Loss: 0.1254, Validation Loss: 0.1151
Epoch 19/20, Loss: 0.1050, Validation Loss: 0.0865
Epoch 20/20, Loss: 0.0842, Validation Loss: 0.0623
Training completed with Overall Loss 0.0623
Predictions:
[[0.]
 [1.]
 [1.]
 [0.]]
Network type: "Regression", layers: 2, neurons: 3, optimizer: "Adam", epochs: 20, batch size: 1, loss function: "Mean Squared Error"
Layer 1, neurons: 2, activation: swish
Neuron 1, inputs: [1 1], weights: [ 1.18 -0.76], bias: -0.0508, z: 0.3743, activation: swish, a: 0.2217
Neuron 2, inputs: [1 1], weights: [ 5.53 -5.

In [79]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(2, activation=swish),
    Layer(output_size, activation=softmax)
], inputs_dim=inputs_dim, loss='categorical_crossentropy', optimizer=Adam())

nn.fit(X_train, y_train, learning_rate=1, epochs=20, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{np.round(predictions)}')

network_summary(nn)

Training started with Overall Loss 0.6964
Epoch 1/20, Loss: 0.8841, Validation Loss: 0.7091
Epoch 3/20, Loss: 0.7043, Validation Loss: 0.6883
Epoch 5/20, Loss: 0.7040, Validation Loss: 0.6817
Epoch 7/20, Loss: 0.6794, Validation Loss: 0.6269
Epoch 9/20, Loss: 0.5221, Validation Loss: 0.4493
Epoch 11/20, Loss: 0.3756, Validation Loss: 0.3294
Epoch 13/20, Loss: 0.2918, Validation Loss: 0.2560
Epoch 15/20, Loss: 0.2206, Validation Loss: 0.1289
Epoch 17/20, Loss: 0.0553, Validation Loss: 0.0278
Epoch 19/20, Loss: 0.0110, Validation Loss: 0.0069
Epoch 20/20, Loss: 0.0063, Validation Loss: 0.0047
Training completed with Overall Loss 0.0047
Predictions:
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]
Network type: "Classification", layers: 2, neurons: 4, optimizer: "Adam", epochs: 20, batch size: 1, loss function: "Categorical Crossentropy"
Layer 1, neurons: 2, activation: swish
Neuron 1, inputs: [1 1], weights: [ 5.34 -5.23], bias: -1.2125, z: -1.1020, activation: swish, a: -0.2748
Neuron 2, inputs: [1