In [1]:
# Импорт библиотек 
import numpy as np

from openneuron.units import Neuron
from openneuron.layers import Layer
from openneuron.models import NeuralNetwork
from openneuron.optimizers import SGD, Adam
from openneuron.functions import *
from openneuron.losses import *
from openneuron.activations import *
from openneuron.utils import *

In [2]:
# Пример решения AND Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [0],
              [0],
              [1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(1, activation=sigmoid)
], inputs_dim=inputs_dim, loss='mse', optimizer=Adam())

nn.fit(X_train, y_train, learning_rate=1, epochs=10, batch_size=1, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{np.round(predictions)}')

network_summary(nn)

Training started with Overall Loss 0.2535
Epoch 1/10, Loss: 0.2951, Validation Loss: 0.2067
Epoch 2/10, Loss: 0.2120, Validation Loss: 0.1925
Epoch 3/10, Loss: 0.1892, Validation Loss: 0.1780
Epoch 4/10, Loss: 0.1703, Validation Loss: 0.1621
Epoch 5/10, Loss: 0.1524, Validation Loss: 0.1462
Epoch 6/10, Loss: 0.1372, Validation Loss: 0.1327
Epoch 7/10, Loss: 0.1267, Validation Loss: 0.1227
Epoch 8/10, Loss: 0.1200, Validation Loss: 0.1147
Epoch 9/10, Loss: 0.1142, Validation Loss: 0.1068
Epoch 10/10, Loss: 0.1073, Validation Loss: 0.0987
Training completed with Overall Loss 0.0987
Predictions:
[[0.]
 [0.]
 [0.]
 [1.]]
Network type: "Classification", layers: 1, neurons: 1, optimizer: "Adam", epochs: 10, batch size: 1, loss function: "Mean Squared Error"
Layer 1, neurons: 1, activation: sigmoid
Neuron 1, inputs: [1 1], weights: [1.15 1.14], bias: -1.82, z: 0.47, activation: linear, a: 0.62


In [3]:
# Пример решения OR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=4, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],
              [1],
              [1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(1, activation=sigmoid)
], inputs_dim=inputs_dim, loss='mse', optimizer=Adam())

nn.fit(X_train, y_train, learning_rate=1, epochs=10, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{np.round(predictions)}')

network_summary(nn)

Training started with Overall Loss 0.2538
Epoch 1/10, Loss: 0.2787, Validation Loss: 0.1830
Epoch 2/10, Loss: 0.1401, Validation Loss: 0.1152
Epoch 3/10, Loss: 0.1025, Validation Loss: 0.0971
Epoch 4/10, Loss: 0.0931, Validation Loss: 0.0907
Epoch 5/10, Loss: 0.0893, Validation Loss: 0.0849
Epoch 6/10, Loss: 0.0845, Validation Loss: 0.0775
Epoch 7/10, Loss: 0.0775, Validation Loss: 0.0685
Epoch 8/10, Loss: 0.0688, Validation Loss: 0.0591
Epoch 9/10, Loss: 0.0596, Validation Loss: 0.0503
Epoch 10/10, Loss: 0.0510, Validation Loss: 0.0429
Training completed with Overall Loss 0.0429
Predictions:
[[0.]
 [1.]
 [1.]
 [1.]]
Network type: "Classification", layers: 1, neurons: 1, optimizer: "Adam", epochs: 10, batch size: 1, loss function: "Mean Squared Error"
Layer 1, neurons: 1, activation: sigmoid
Neuron 1, inputs: [1 1], weights: [2.5354 2.2221], bias: -0.57, z: 4.19, activation: linear, a: 0.99


In [6]:
# Пример решения AND Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=4, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [0],
              [0],
              [1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer([
        Neuron(weights=[0.45, -0.12], bias=1.0)
    ], activation=sigmoid)
], inputs_dim=inputs_dim, loss='mse', optimizer=SGD(momentum=0.3))

nn.fit(X_train, y_train, learning_rate=0.7, epochs=100, batch_size=1, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{predictions}')

network_summary(nn)

Training started with Overall Loss 0.4335
Epoch 1/100, Loss: 0.4319, Validation Loss: 0.3012
Epoch 11/100, Loss: 0.1322, Validation Loss: 0.1043
Epoch 21/100, Loss: 0.0793, Validation Loss: 0.0651
Epoch 31/100, Loss: 0.0548, Validation Loss: 0.0467
Epoch 41/100, Loss: 0.0411, Validation Loss: 0.0360
Epoch 51/100, Loss: 0.0326, Validation Loss: 0.0291
Epoch 61/100, Loss: 0.0268, Validation Loss: 0.0243
Epoch 71/100, Loss: 0.0226, Validation Loss: 0.0208
Epoch 81/100, Loss: 0.0195, Validation Loss: 0.0181
Epoch 91/100, Loss: 0.0171, Validation Loss: 0.0160
Epoch 100/100, Loss: 0.0154, Validation Loss: 0.0145
Training completed with Overall Loss 0.0145
Predictions:
[[0.0041]
 [0.1311]
 [0.1338]
 [0.8492]]
Network type: "Classification", layers: 1, neurons: 1, optimizer: "SGD" with momentum 0.3, epochs: 100, batch size: 1, loss function: "Mean Squared Error"
Layer 1, neurons: 1, activation: sigmoid
Neuron 1, inputs: [1 1], weights: [3.6191 3.5961], bias: -5.49, z: 1.73, activation: linear,