In [19]:
# Импорт библиотек 
import numpy as np

from openneuron.units import Neuron
from openneuron.layers import Layer
from openneuron.models import NeuralNetwork
from openneuron.optimizers import SGD, Adam
from openneuron.functions import *
from openneuron.losses import *
from openneuron.activations import *
from openneuron.utils import *

In [20]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=4, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

nn = NeuralNetwork([
    Layer([
        Neuron(weights=[-1.01, 0.05], bias=-0.09),
        Neuron(weights=[0.02, -2.06], bias=0.10),
    ], activation=swish),
    Layer([
        Neuron(weights=[-3.03, 0.07], bias=-0.11),
        Neuron(weights=[0.04, -4.08], bias=0.12),
    ], activation=softmax)
], inputs_dim=inputs_dim, loss='categorical_crossentropy', optimizer=SGD(learning_rate=0.75))

nn.fit(X_train, y_train, epochs=10)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{predictions}')

network_summary(nn)

Training started with Overall Loss 0.7642 on Train Data
Epoch 1/10, Loss: 1.3110, Validation Loss: 0.6908 on Train Data
Epoch 2/10, Loss: 0.9442, Validation Loss: 0.5908 on Train Data
Epoch 3/10, Loss: 0.7348, Validation Loss: 0.4850 on Train Data
Epoch 4/10, Loss: 0.5600, Validation Loss: 0.3911 on Train Data
Epoch 5/10, Loss: 0.5110, Validation Loss: 0.3506 on Train Data
Epoch 6/10, Loss: 0.4607, Validation Loss: 0.3132 on Train Data
Epoch 7/10, Loss: 0.3916, Validation Loss: 0.2948 on Train Data
Epoch 8/10, Loss: 0.3524, Validation Loss: 0.2676 on Train Data
Epoch 9/10, Loss: 0.3423, Validation Loss: 0.2550 on Train Data
Epoch 10/10, Loss: 0.3113, Validation Loss: 0.2307 on Train Data
Training completed with Overall Loss 0.2307
Predictions:
[[0.1069 0.8931]
 [0.6527 0.3473]
 [0.997  0.003 ]
 [0.3162 0.6838]]
Network type: "Classification", layers: 2, neurons: 4, optimizer: "SGD" with momentum 0, epochs: 10, batch size: 1, loss function: "Categorical Crossentropy"
Layer 1, neurons: 2

In [27]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(4, activation=swish),
    Layer(2, activation=softmax)
], inputs_dim=inputs_dim, loss='categorical_crossentropy', optimizer=Adam(learning_rate=1))

nn.fit(X_train, y_train, epochs=10, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{predictions}')

network_summary(nn)

Training started with Overall Loss 0.7073 on Train Data
Epoch 1/10, Loss: 1.0308, Validation Loss: 0.7090 on Train Data
Epoch 2/10, Loss: 0.7327, Validation Loss: 0.6896 on Train Data
Epoch 3/10, Loss: 0.7010, Validation Loss: 0.6818 on Train Data
Epoch 4/10, Loss: 0.6938, Validation Loss: 0.6755 on Train Data
Epoch 5/10, Loss: 0.6919, Validation Loss: 0.6673 on Train Data
Epoch 6/10, Loss: 0.6858, Validation Loss: 0.6523 on Train Data
Epoch 7/10, Loss: 0.6715, Validation Loss: 0.6226 on Train Data
Epoch 8/10, Loss: 0.6408, Validation Loss: 0.5608 on Train Data
Epoch 9/10, Loss: 0.5698, Validation Loss: 0.4407 on Train Data
Epoch 10/10, Loss: 0.4295, Validation Loss: 0.2976 on Train Data
Training completed with Overall Loss 0.2976
Predictions:
[[0.09 0.91]
 [0.95 0.05]
 [0.57 0.43]
 [0.38 0.62]]
Network type: "Classification", layers: 2, neurons: 6, optimizer: "Adam", epochs: 10, batch size: 1, loss function: "Categorical Crossentropy"
Layer 1, neurons: 4, activation: swish
Neuron 1, i

In [22]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(2, activation=swish),
    Layer(1, activation=sigmoid)
], inputs_dim=inputs_dim, loss='mse', optimizer=Adam(learning_rate=1))

nn.fit(X_train, y_train, epochs=20, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{np.round(predictions)}')

network_summary(nn)

Training started with Overall Loss 0.2845 on Train Data
Epoch 1/20, Loss: 0.2960, Validation Loss: 0.2540 on Train Data
Epoch 2/20, Loss: 0.2574, Validation Loss: 0.2496 on Train Data
Epoch 4/20, Loss: 0.2499, Validation Loss: 0.2420 on Train Data
Epoch 6/20, Loss: 0.2326, Validation Loss: 0.2050 on Train Data
Epoch 8/20, Loss: 0.1571, Validation Loss: 0.1310 on Train Data
Epoch 10/20, Loss: 0.1129, Validation Loss: 0.1021 on Train Data
Epoch 12/20, Loss: 0.0861, Validation Loss: 0.0788 on Train Data
Epoch 14/20, Loss: 0.0643, Validation Loss: 0.0483 on Train Data
Epoch 16/20, Loss: 0.0424, Validation Loss: 0.0205 on Train Data
Epoch 18/20, Loss: 0.0096, Validation Loss: 0.0066 on Train Data
Epoch 20/20, Loss: 0.0027, Validation Loss: 0.0025 on Train Data
Training completed with Overall Loss 0.0025
Predictions:
[[0.]
 [1.]
 [1.]
 [0.]]
Network type: "Classification", layers: 2, neurons: 3, optimizer: "Adam", epochs: 20, batch size: 1, loss function: "Mean Squared Error"
Layer 1, neuron

In [23]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0, 1],
              [1, 0],
              [1, 0],
              [0, 1]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer(2, activation=swish),
    Layer(output_size, activation=softmax)
], inputs_dim=inputs_dim, loss='categorical_crossentropy', optimizer=Adam(learning_rate=1))

nn.fit(X_train, y_train, epochs=20, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{np.round(predictions)}')

network_summary(nn)

Training started with Overall Loss 0.7087 on Train Data
Epoch 1/20, Loss: 0.9702, Validation Loss: 0.7564 on Train Data
Epoch 2/20, Loss: 0.7664, Validation Loss: 0.6992 on Train Data
Epoch 4/20, Loss: 0.7052, Validation Loss: 0.7013 on Train Data
Epoch 6/20, Loss: 0.7097, Validation Loss: 0.6801 on Train Data
Epoch 8/20, Loss: 0.6534, Validation Loss: 0.5391 on Train Data
Epoch 10/20, Loss: 0.2409, Validation Loss: 0.1374 on Train Data
Epoch 12/20, Loss: 0.0361, Validation Loss: 0.0168 on Train Data
Epoch 14/20, Loss: 0.0081, Validation Loss: 0.0061 on Train Data
Epoch 16/20, Loss: 0.0036, Validation Loss: 0.0030 on Train Data
Epoch 18/20, Loss: 0.0020, Validation Loss: 0.0018 on Train Data
Epoch 20/20, Loss: 0.0013, Validation Loss: 0.0012 on Train Data
Training completed with Overall Loss 0.0012
Predictions:
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]
Network type: "Classification", layers: 2, neurons: 4, optimizer: "Adam", epochs: 20, batch size: 1, loss function: "Categorical Crossentrop

In [24]:
# Пример решения XOR Classificator
# Настройка вывода для удобочитаемости
np.set_printoptions(precision=2, suppress=True, threshold=8, edgeitems=1, linewidth=80)

# XOR Categorical
X = np.array([[0, 0], 
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0],
              [1],
              [1],
              [0]])

X_train, y_train = X, y
X_test, y_test = X, y

# Размерность входных и выходных данных
inputs_dim = X_train.shape[1]
output_size = y_train.shape[1]

# Создание и обучение модели
nn = NeuralNetwork([
    Layer([
        Neuron(weights=[0.45, -0.12], bias=1.0),
        Neuron(weights=[0.78, 0.13], bias=1.0),
    ], activation=sigmoid),
    Layer([
        Neuron(weights=[1.5, -2.3], bias=1.0)
    ], activation=sigmoid)
], inputs_dim=inputs_dim, loss='mse', optimizer=SGD(learning_rate=0.7, momentum=0.3))

nn.fit(X_train, y_train, epochs=100, batch_size=4, shuffle=False)

# Предсказание на тестовых данных
predictions = nn.predict(X_test)
print(f'Predictions:\n{predictions}')

network_summary(nn)

Training started with Overall Loss 0.2574 on Train Data
Epoch 1/100, Loss: 0.2574, Validation Loss: 0.2555 on Train Data
Epoch 10/100, Loss: 0.2515, Validation Loss: 0.2514 on Train Data
Epoch 20/100, Loss: 0.2503, Validation Loss: 0.2501 on Train Data
Epoch 30/100, Loss: 0.2492, Validation Loss: 0.2491 on Train Data
Epoch 40/100, Loss: 0.2482, Validation Loss: 0.2481 on Train Data
Epoch 50/100, Loss: 0.2473, Validation Loss: 0.2472 on Train Data
Epoch 60/100, Loss: 0.2464, Validation Loss: 0.2463 on Train Data
Epoch 70/100, Loss: 0.2454, Validation Loss: 0.2453 on Train Data
Epoch 80/100, Loss: 0.2444, Validation Loss: 0.2443 on Train Data
Epoch 90/100, Loss: 0.2433, Validation Loss: 0.2431 on Train Data
Epoch 100/100, Loss: 0.2420, Validation Loss: 0.2418 on Train Data
Training completed with Overall Loss 0.2418
Predictions:
[[0.48]
 [0.58]
 [0.43]
 [0.49]]
Network type: "Classification", layers: 2, neurons: 7, optimizer: "SGD" with momentum 0.3, epochs: 100, batch size: 4, loss func